config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:edit, :update, :show]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :flats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
     @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  private
  def booking_params
    params.require(:booking).permit(:message)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:query]
      @flats = Flat.search_by_name_and_address(params[:query])
    else
    @flats = Flat.all
  end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])

  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
  end

private

  def flat_params
    params.require(:flat).permit(:name, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = @user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@flat, @booking] do |f| %>
<%= f.input :message %>
<%= f.submit :submit %>
<% end %>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
Your message: <%= @booking.message %> <br>
Your booking name of flat: <%= @booking.flat.name %>

<%= link_to 'edit this booking', edit_booking_path(@booking) %>

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.submit :submit %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<%= form_tag flats_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a flat"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<ul>
<% @flats.each do |flat| %>
<li>
<%= link_to flat.name, flat_path(flat) %></li>
<% end %>
</ul>


  <% if params[:query] %>
  <%= link_to 'back to all flats', flats_path %>
  <% end %>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/show.html.erb
<%= @flat.name %>
<p><%= @flat.address %></p>

User is: <%= @flat.user.email %>

<%= link_to 'back', flats_path %><br>

<% if @flat.user == current_user %>
<%= link_to "edit #{ @flat.name}", edit_flat_path(@flat) %>
<%= link_to "delete #{ @flat.name}",  flat_path(@flat), method: :delete%>
<% else %>
<%= link_to "Book #{@flat.name}", new_flat_booking_path(@flat)  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbLucy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", flats_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Flat", new_flat_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "View all flats", flats_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<% @bookings.each do |b| %>
<%= b.flat.name %>
<br>
Your message <%= b.message %>
<% end %>

<h1>Your flats</h1>
<% @user.flats.each do |f|  %>
<%= f.name %>
<% end %>

<%= link_to 'new flat', new_flat_path %>